### PR TITLE
fix: prevent no-code ndoes from being returned from the graph

### LINKED ISSUE #1165: filter stakgraph_search
only code nodes. no Hint nodes

### PR DESCRIPTION
**Pull request by fayekelmith**
Closes #1165

### CODE REVIEW

File: mcp/src/graph/graph.ts [hunk 1]
```diff
@@ -80,8 +80,8 @@ export async function search(
   sortBy: SearchSortBy = "relevance"
 ) {
   const skip_node_types: NodeType[] = tests
-    ? []
-    : (["UnitTest", "IntegrationTest", "E2etest"] as NodeType[]);
+    ? (["Hint", "Prompt", "PullRequest", "Mock", "Learning", "Scope"] as NodeType[])
```
Comment (Evanfeenstra) [inline mcp/src/graph/graph.ts]: only source code nodes for stakgraph_search. We can have any number of node types in production graphs
